version: '3.4'

networks:
  k6:
  grafana:
  chronograf:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
      - chronograf
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      
  chronograf:
     image: chronograf:latest
     networks:
      - k6
      - grafana
      - chronograf
     ports:
      - '8888:8888'
     volumes:
      - chronograf-storage:/var/lib/chronograf
     depends_on:
      - influxdb
     environment:
      - INFLUXDB_URL=http://influxdb:8086

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    env_file:
      - .env
    volumes:
      - ./dist:/dist
volumes:
  chronograf-storage:
